add_library(openfilter_gate_engine STATIC Engine.cpp)
target_include_directories(openfilter_gate_engine PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}")
target_link_libraries(openfilter_gate_engine PUBLIC openfilter_dsp openfilter_parameters PRIVATE openfilter_options)
set_target_properties(openfilter_gate_engine PROPERTIES CXX_VISIBILITY_PRESET hidden VISIBILITY_INLINES_HIDDEN YES)
add_library(openfilter_gate_editor STATIC Editor.cpp)
target_link_libraries(openfilter_gate_editor PUBLIC openfilter_gate_engine openfilter_ui PRIVATE openfilter_options)
set_target_properties(openfilter_gate_editor PROPERTIES CXX_VISIBILITY_PRESET hidden VISIBILITY_INLINES_HIDDEN YES)
add_library(OpenFilterGate MODULE Plugin.cpp)
target_link_libraries(OpenFilterGate PRIVATE openfilter_gate_engine openfilter_gate_editor openfilter_plugin openfilter_options)
set_target_properties(OpenFilterGate PROPERTIES PREFIX "" SUFFIX ".clap" CXX_VISIBILITY_PRESET hidden
  VISIBILITY_INLINES_HIDDEN YES LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/plugins")
if(UNIX AND NOT APPLE)
  install(TARGETS OpenFilterGate LIBRARY DESTINATION lib/clap)
endif()
