#pragma once
#include "Filter.hpp"
#include <array>

namespace openfilter::dsp {
// Independent 20th-order elliptic cut: 0.01 dB passband ripple, 100 dB stopband.
// Frequency is the passband edge. No lookahead/block latency; phase is nonlinear.
// Fixed prototype generated by tools/design_brickwall.py (SciPy ellipap).
// Each row is {pole magnitude, damping, pole magnitude squared / zero squared}.
inline constexpr unsigned brickwallStages = 10;
inline constexpr std::array<std::array<double, 3>, brickwallStages> brickwallPrototype{{
    {0.41735734388243118, 1.8107204437245317, 0.0040434194799715637},
    {0.57685057127554829, 1.0634030632445521, 0.061587569672657931},
    {0.73842874795459279, 0.57243024257610675, 0.22617749820553576},
    {0.8512757128448738, 0.30736467750222152, 0.45009434589043262},
    {0.92016271757176871, 0.16518306206036432, 0.65067570694349686},
    {0.9596522700658775, 0.088654149667171805, 0.79302264064952543},
    {0.98152426858729314, 0.047272928071675303, 0.88163089769599312},
    {0.9932983573704246, 0.024618579398449716, 0.93242830712819713},
    {0.99930321145418555, 0.011714427563770264, 0.9592032374512095},
    {1.0018202035357566, 0.0034494617932724256, 0.9706040840382012},
}};
inline Coefficients brickwallSection(bool highpass, unsigned stage, double warped) noexcept {
    const auto &p = brickwallPrototype[stage];
    const double g = highpass ? warped / p[0] : warped * p[0], k = p[1], h = p[2];
    Coefficients c;
    c.a1 = 1 / (1 + g * (g + k));
    c.a2 = g * c.a1;
    c.a3 = g * c.a2;
    c.m0 = highpass ? 1 : h;
    c.m1 = -k * c.m0;
    c.m2 = highpass ? h - 1 : 1 - h;
    if (stage == 0) {
        constexpr double normalization = 0.99884936993650519;
        c.m0 *= normalization;
        c.m1 *= normalization;
        c.m2 *= normalization;
    }
    return c;
}
} // namespace openfilter::dsp
