add_library(openfilter_limiter_engine STATIC Engine.cpp ModernEngine.cpp LegacyEngine.cpp)
target_include_directories(openfilter_limiter_engine PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}")
target_link_libraries(openfilter_limiter_engine PUBLIC openfilter_dsp openfilter_parameters PRIVATE openfilter_options)
set_target_properties(openfilter_limiter_engine PROPERTIES CXX_VISIBILITY_PRESET hidden VISIBILITY_INLINES_HIDDEN YES)
add_library(openfilter_limiter_editor STATIC Editor.cpp)
target_link_libraries(openfilter_limiter_editor PUBLIC openfilter_limiter_engine openfilter_ui PRIVATE openfilter_options)
set_target_properties(openfilter_limiter_editor PROPERTIES CXX_VISIBILITY_PRESET hidden VISIBILITY_INLINES_HIDDEN YES)
add_library(OpenFilterLimiter MODULE Plugin.cpp)
target_link_libraries(OpenFilterLimiter PRIVATE openfilter_limiter_engine openfilter_limiter_editor openfilter_plugin openfilter_options)
set_target_properties(OpenFilterLimiter PROPERTIES PREFIX "" SUFFIX ".clap" CXX_VISIBILITY_PRESET hidden
  VISIBILITY_INLINES_HIDDEN YES LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/plugins")
if(UNIX AND NOT APPLE)
  install(TARGETS OpenFilterLimiter LIBRARY DESTINATION lib/clap)
endif()
