add_library(openfilter_compressor_engine STATIC Engine.cpp)
target_include_directories(openfilter_compressor_engine PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}")
target_link_libraries(openfilter_compressor_engine PUBLIC openfilter_dsp openfilter_parameters PRIVATE openfilter_options)
set_target_properties(openfilter_compressor_engine PROPERTIES CXX_VISIBILITY_PRESET hidden VISIBILITY_INLINES_HIDDEN YES)
add_library(openfilter_compressor_editor STATIC Editor.cpp)
target_link_libraries(openfilter_compressor_editor PUBLIC openfilter_compressor_engine openfilter_ui PRIVATE openfilter_options)
set_target_properties(openfilter_compressor_editor PROPERTIES CXX_VISIBILITY_PRESET hidden VISIBILITY_INLINES_HIDDEN YES)
add_library(OpenFilterCompressor MODULE Plugin.cpp)
target_link_libraries(OpenFilterCompressor PRIVATE openfilter_compressor_engine openfilter_compressor_editor openfilter_plugin openfilter_options)
set_target_properties(OpenFilterCompressor PROPERTIES PREFIX "" SUFFIX ".clap" CXX_VISIBILITY_PRESET hidden
  VISIBILITY_INLINES_HIDDEN YES LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/plugins")
if(UNIX AND NOT APPLE)
  install(TARGETS OpenFilterCompressor LIBRARY DESTINATION lib/clap)
endif()
