add_library(openfilter_reverb_engine STATIC Engine.cpp)
target_include_directories(openfilter_reverb_engine PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}")
target_link_libraries(openfilter_reverb_engine PUBLIC openfilter_dsp openfilter_parameters PRIVATE openfilter_options)
set_target_properties(openfilter_reverb_engine PROPERTIES CXX_VISIBILITY_PRESET hidden VISIBILITY_INLINES_HIDDEN YES)
add_library(openfilter_reverb_editor STATIC Editor.cpp)
target_link_libraries(openfilter_reverb_editor PUBLIC openfilter_reverb_engine openfilter_ui PRIVATE openfilter_options)
set_target_properties(openfilter_reverb_editor PROPERTIES CXX_VISIBILITY_PRESET hidden VISIBILITY_INLINES_HIDDEN YES)
add_library(OpenFilterReverb MODULE Plugin.cpp)
target_link_libraries(OpenFilterReverb PRIVATE openfilter_reverb_engine openfilter_reverb_editor openfilter_plugin openfilter_options)
set_target_properties(OpenFilterReverb PROPERTIES PREFIX "" SUFFIX ".clap" CXX_VISIBILITY_PRESET hidden
  VISIBILITY_INLINES_HIDDEN YES LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/plugins")
if(UNIX AND NOT APPLE)
  install(TARGETS OpenFilterReverb LIBRARY DESTINATION lib/clap)
endif()
