add_library(openfilter_dsp INTERFACE)
target_include_directories(openfilter_dsp INTERFACE dsp/include)
add_library(openfilter_parameters INTERFACE)
target_include_directories(openfilter_parameters INTERFACE parameters/include)
add_library(openfilter_plugin INTERFACE)
target_include_directories(openfilter_plugin INTERFACE plugin/include)
target_link_libraries(openfilter_plugin INTERFACE clap-helpers)
add_library(openfilter_ui INTERFACE)
target_include_directories(openfilter_ui INTERFACE ui/include)
target_link_libraries(openfilter_ui INTERFACE openfilter_plugin openfilter_pugl)
