add_library(openfilter_saturator_engine STATIC Engine.cpp)
target_include_directories(openfilter_saturator_engine PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}")
target_link_libraries(openfilter_saturator_engine PUBLIC openfilter_dsp openfilter_parameters PRIVATE openfilter_options)
set_target_properties(openfilter_saturator_engine PROPERTIES CXX_VISIBILITY_PRESET hidden VISIBILITY_INLINES_HIDDEN YES)
add_library(openfilter_saturator_editor STATIC Editor.cpp)
target_link_libraries(openfilter_saturator_editor PUBLIC openfilter_saturator_engine openfilter_ui PRIVATE openfilter_options)
set_target_properties(openfilter_saturator_editor PROPERTIES CXX_VISIBILITY_PRESET hidden VISIBILITY_INLINES_HIDDEN YES)
add_library(OpenFilterSaturator MODULE Plugin.cpp)
target_link_libraries(OpenFilterSaturator PRIVATE openfilter_saturator_engine openfilter_saturator_editor openfilter_plugin openfilter_options)
set_target_properties(OpenFilterSaturator PROPERTIES PREFIX "" SUFFIX ".clap" CXX_VISIBILITY_PRESET hidden
  VISIBILITY_INLINES_HIDDEN YES LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/plugins")
if(UNIX AND NOT APPLE)
  install(TARGETS OpenFilterSaturator LIBRARY DESTINATION lib/clap)
endif()
