#!/usr/bin/env python3
"""Compile the shipped SVG wordmarks into native Cairo drawing commands.

No runtime SVG parser or asset files are required. This deliberately accepts only
the flattened, absolute M/L/H/V/C/Z paths in our Figma exports, failing on other
SVG features instead of silently changing artwork. Run after editing the SVGs.
"""
from pathlib import Path
import hashlib
import re
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
NS = "{http://www.w3.org/2000/svg}"


def commands(data):
    tokens = re.findall(r"[A-Za-z]|[-+]?(?:\d*\.\d+|\d+\.?\d*)(?:[eE][-+]?\d+)?", data)
    if re.sub(r"[\s,]", "", data) != "".join(tokens):
        raise ValueError("Unexpected SVG path syntax")
    arity = {"M": 2, "L": 2, "H": 1, "V": 1, "C": 6}
    i, x, y, start_x, start_y = 0, 0., 0., 0., 0.
    command = None
    while i < len(tokens):
        if tokens[i].isalpha():
            command = tokens[i]
            i += 1
            if command == "Z":
                yield "cairo_close_path(c);"
                x, y = start_x, start_y
                command = None
                continue
        if command not in arity:
            raise ValueError(f"Unsupported SVG command {command}")
        n = arity[command]
        values = [float(t) for t in tokens[i:i + n]]
        if len(values) != n:
            raise ValueError("Incomplete SVG command")
        i += n
        if command == "H":
            values = [values[0], y]
        elif command == "V":
            values = [x, values[0]]
        operation = "curve_to" if command == "C" else "move_to" if command == "M" else "line_to"
        x, y = values[-2:]
        if command == "M":
            start_x, start_y = x, y
            command = "L"
        yield f"cairo_{operation}(c, {', '.join(format(v, '.9g') for v in values)});"


def generate():
    lines = ["// Generated by tools/generate_brand_paths.py; edit assets/branding/*.svg instead.",
             "#pragma once", '#include "Draw.hpp"', "", "namespace openfilter::ui::brand_detail {"]
    for name, symbol in (("eq", "eq"), ("compressor", "compressor"), ("limiter", "limiter")):
        data = (ROOT / f"assets/branding/openfilter-{name}.svg").read_bytes()
        svg = ET.fromstring(data)
        bounds = [float(v) for v in svg.attrib["viewBox"].split()]
        lines += [f"// SVG SHA-256: {hashlib.sha256(data).hexdigest()}",
                  f"inline constexpr Rect {symbol}Bounds{{{', '.join(format(v, '.9g') for v in bounds)}}};",
                  f"inline void {symbol}(cairo_t *c) {{"]
        for path in svg:
            if path.tag == NS + "title":
                continue
            if path.tag != NS + "path" or set(path.attrib) - {"d", "fill", "fill-rule"}:
                raise ValueError("Expected flattened paths with solid fills")
            fill = path.attrib["fill"]
            if not re.fullmatch(r"#[0-9A-Fa-f]{6}", fill):
                raise ValueError("Expected RGB hex color")
            rule = {"nonzero": "WINDING", "evenodd": "EVEN_ODD"}[path.get("fill-rule", "nonzero")]
            lines += [f"    color(c, hex(0x{fill[1:]}));",
                      f"    cairo_set_fill_rule(c, CAIRO_FILL_RULE_{rule});", "    cairo_new_path(c);"]
            lines.extend("    " + line for line in commands(path.attrib["d"]))
            lines.append("    cairo_fill(c);")
        lines += ["}", ""]
    lines.append("} // namespace openfilter::ui::brand_detail")
    (ROOT / "libs/ui/include/openfilter/ui/BrandPaths.hpp").write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    generate()
