add_library(openfilter_eq_engine STATIC Engine.cpp)
target_include_directories(openfilter_eq_engine PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}")
target_link_libraries(openfilter_eq_engine PUBLIC openfilter_dsp openfilter_parameters PRIVATE openfilter_options)
set_target_properties(openfilter_eq_engine PROPERTIES CXX_VISIBILITY_PRESET hidden VISIBILITY_INLINES_HIDDEN YES)
add_library(openfilter_eq_editor STATIC Editor.cpp)
target_link_libraries(openfilter_eq_editor PUBLIC openfilter_eq_engine openfilter_ui PRIVATE openfilter_options)
set_target_properties(openfilter_eq_editor PROPERTIES CXX_VISIBILITY_PRESET hidden VISIBILITY_INLINES_HIDDEN YES)
add_library(OpenFilterEQ MODULE Plugin.cpp)
target_link_libraries(OpenFilterEQ PRIVATE openfilter_eq_engine openfilter_eq_editor openfilter_plugin openfilter_options)
set_target_properties(OpenFilterEQ PROPERTIES PREFIX "" SUFFIX ".clap" CXX_VISIBILITY_PRESET hidden
  VISIBILITY_INLINES_HIDDEN YES LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/plugins")
if(UNIX AND NOT APPLE)
  install(TARGETS OpenFilterEQ LIBRARY DESTINATION lib/clap)
endif()
