add_library(openfilter_deesser_engine STATIC Engine.cpp)
target_include_directories(openfilter_deesser_engine PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}")
target_link_libraries(openfilter_deesser_engine PUBLIC openfilter_dsp openfilter_parameters PRIVATE openfilter_options)
set_target_properties(openfilter_deesser_engine PROPERTIES CXX_VISIBILITY_PRESET hidden VISIBILITY_INLINES_HIDDEN YES)
add_library(openfilter_deesser_editor STATIC Editor.cpp)
target_link_libraries(openfilter_deesser_editor PUBLIC openfilter_deesser_engine openfilter_ui PRIVATE openfilter_options)
set_target_properties(openfilter_deesser_editor PROPERTIES CXX_VISIBILITY_PRESET hidden VISIBILITY_INLINES_HIDDEN YES)
add_library(OpenFilterDeesser MODULE Plugin.cpp)
target_link_libraries(OpenFilterDeesser PRIVATE openfilter_deesser_engine openfilter_deesser_editor openfilter_plugin openfilter_options)
set_target_properties(OpenFilterDeesser PROPERTIES PREFIX "" SUFFIX ".clap" CXX_VISIBILITY_PRESET hidden
  VISIBILITY_INLINES_HIDDEN YES LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/plugins")
if(UNIX AND NOT APPLE)
  install(TARGETS OpenFilterDeesser LIBRARY DESTINATION lib/clap)
endif()
